# Importing Library

In [39]:
import pandas as pd

# Loading  dataset

In [40]:

df = pd.read_csv('customer_shopping_behavior.csv')

# Displaying the first 5 rows of the dataset

In [41]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

# Checking dataset information such as columns, data types, and null values

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

# Checking missing values in each column

In [43]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

# Filling missing values in 'Review Rating' using category-wise median

In [44]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

# Verifying if missing values have been handled

In [45]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

# Converting column names to lowercase

In [46]:
df.columns = df.columns.str.lower()

# Replacing spaces with underscore in column names
df.columns = df.columns.str.replace(' ','_')

# Renaming purchase amount column
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

# Displaying updated column names

In [47]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

# create a new column

In [48]:
labels = ['Young Adults', 'Adult', 'Middle-Aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

# Viewing age and corresponding age group columns

In [49]:
df[['age', 'age_group']].head(10)

   age     age_group
0   55   Middle-Aged
1   19  Young Adults
2   50   Middle-Aged
3   21  Young Adults
4   45   Middle-Aged
5   46   Middle-Aged
6   63        Senior
7   27  Young Adults
8   26  Young Adults
9   57   Middle-Aged

# create column purchase_frequency_days

In [50]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

# Displaying purchase frequency columns

In [51]:
print(df[['purchase_frequency_days','frequency_of_purchases']].head(10))

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

# Checking discount applied and promo code used columns

In [52]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

# Checking whether both columns contain same values or not

In [53]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

# Dropping promo_code_used column because it contains duplicate information

In [54]:
df = df.drop(columns='promo_code_used', axis=1)

# Displaying final cleaned column names

In [55]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

# Connect to MySQL

# Install Required Libraries

In [56]:
!pip install pymysql

Requirement already satisfied: pymysql in C:\Users\Himanshu\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.2.0)

In [57]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in C:\Users\Himanshu\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in C:\Users\Himanshu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Himanshu\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sqlalchemy) (4.13.2)

# Establish Connection

In [ ]:
# Step 1: Establish a Connection to MySQL

from sqlalchemy import create_engine
username = "root"
password = "your_password"
host = "localhost"
port = "3306"
database = "customer_behavior"

engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')

# Step 2: Load the DataFrame into MySQL

table_name = "customer"
df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)

print(f"Data successfully loaded into MySQL table '{table_name}' in database '{database}'.")

Data successfully loaded into MySQL table 'customer' in database 'customer_behavior'.